### ISSUE TITLE
BiG-MAP.download.py can't download test-set: ftp site is decommissioned

### ISSUE THREAD

**Issue by edissepo** [medema-group/BiG-MAP#2]
Upon trying to download the test project as provided in the readme, an error occurs claiming that the site cannot be accessed (No such directory ‘sra/sra-instant/reads/ByRun/sra/SRR/SRR013/SRR013549’.) - see below for full error code.
Trying manually with wget gives the same error.
Found online an explanation (https://ncbiinsights.ncbi.nlm.nih.gov/2019/10/17/users-of-the-sra-ftp-site-try-the-sra-toolkit/) - the ncbi ftp site is decommissioned since December 2019.

Solve:
Try incorporating the SRA-tool in BiG-MAP.download.py

Good luck.

Error:
Namespace(acclist='../SRR_Acc_List.txt', outdir='../../scratch/')
--2020-10-19 12:24:37--  ftp://ftp-trace.ncbi.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR013/SRR013549/SRR013549.sra
           => ‘../../scratch/SRR013549.sra’
Resolving ftp-trace.ncbi.nih.gov (ftp-trace.ncbi.nih.gov)... 130.14.250.11, 2607:f220:41e:250::10, 2607:f220:41e:250::13, ...
Connecting to ftp-trace.ncbi.nih.gov (ftp-trace.ncbi.nih.gov)|130.14.250.11|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /sra/sra-instant/reads/ByRun/sra/SRR/SRR013/SRR013549 ...
No such directory ‘sra/sra-instant/reads/ByRun/sra/SRR/SRR013/SRR013549’.

Traceback (most recent call last):
  File "BiG-MAP.download.py", line 194, in <module>
    main()
  File "BiG-MAP.download.py", line 188, in main
    downloadSRA(acc, args.outdir)
  File "BiG-MAP.download.py", line 127, in downloadSRA
    res_download = subprocess.check_output(cmd_download, shell=True)
  File "/opt/miniconda3/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/opt/miniconda3/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'wget ftp://ftp-trace.ncbi.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR013/SRR013549/SRR013549.sra -P ../../scratch/' returned non-zero exit status 8.

**Comment by victoriapascal** [comment]
I have just done a test with the data and command from the tutorial and I can't reproduce your error. Did you activate the BiG-MAP_process environment? What command did you use exactly? Do you have permission to create a new folders?
