### ISSUE TITLE
Hi BiG-MAP team,

### ISSUE THREAD

**Issue by hildaha** [medema-group/BiG-MAP#23]
I am having a problem with running the BiG-MAP analysis module. The problem seems to be related the metadata 'sample type'
Kindly assist.

#my command
 python3 BiG-MAP.analyse.py --explore --compare -B /home/hildaha/BiG-MAP/Analysis/results_Mapping/biom-results/BiG-MAP.map.meta.dec.biom -T metagenomic -M Amendment -g CF NCF -O /home/hildaha/BiG-MAP/Analysis/results_analysis/

Attached also is the metadata file I used in mapping module

[metadata.txt](https://github.com/medema-group/BiG-MAP/files/12301204/metadata.txt)

#Here is the error I get.
__________Loading biom file_______________________
Traceback (most recent call last):
  File "BiG-MAP.analyse.py", line 1229, in <module>
    main()
  File "BiG-MAP.analyse.py", line 1061, in main
    biom_dict, args.metagroup)
  File "BiG-MAP.analyse.py", line 153, in get_sample_type
    elif sample_type == (sample["metadata"]["SampleType"]).upper():
KeyError: 'SampleType'

**Comment by akbrand6** [comment]
I'm not part of the team, and I don't really know what I'm doing.   But I had the same issue, in my metadata file I had a column called `sample-type`.  so of course it shows up in my .biom file.   I changed `sample-type` to `SampleType` in my biom file and somehow that fixed it.    I think it is looking for that specific format in the biom file.
