### ISSUE TITLE
BiG-MAP.map.py type error

### ISSUE THREAD

**Issue by Lachlan1991** [medema-group/BiG-MAP#26]
I'm trying to run BiG-MAP on a set of metatranscriptome samples. The family module is prepared from antiSMASH input of isolate genomes, which I am trying to map my RNA reads to. I had to rename my fastq files based on a previous issue with underscores, so they are named 1_R1.fastq, 1_R2.fastq etc. 
The mapping stage begins and bowtie does start mapping, but quickly aborts. The error reads below:

Loading big-map/230322
  Loading requirement: python/3.9.4 R/4.0.5 gsl/2.6 capnproto-c++/0.9.1 mash/2.3
    fasttree/2.1.11 hmmer/3.4.0 scikit-learn/1.1.2-py39 big-scape/1.1.5
Building a SMALL index
Renaming /scratch3/dow17n/RNA_pilot/big-map/big-map_map_output_sorangium/BiG-MAP.GCF_HGF.3.bt2.tmp to /scratch3/dow17n/RNA_pilot/big-map/big-map_map_output_sorangium/BiG-MAP.GCF_HGF.3.bt2
Renaming /scratch3/dow17n/RNA_pilot/big-map/big-map_map_output_sorangium/BiG-MAP.GCF_HGF.4.bt2.tmp to /scratch3/dow17n/RNA_pilot/big-map/big-map_map_output_sorangium/BiG-MAP.GCF_HGF.4.bt2
Renaming /scratch3/dow17n/RNA_pilot/big-map/big-map_map_output_sorangium/BiG-MAP.GCF_HGF.1.bt2.tmp to /scratch3/dow17n/RNA_pilot/big-map/big-map_map_output_sorangium/BiG-MAP.GCF_HGF.1.bt2
Renaming /scratch3/dow17n/RNA_pilot/big-map/big-map_map_output_sorangium/BiG-MAP.GCF_HGF.2.bt2.tmp to /scratch3/dow17n/RNA_pilot/big-map/big-map_map_output_sorangium/BiG-MAP.GCF_HGF.2.bt2
Renaming /scratch3/dow17n/RNA_pilot/big-map/big-map_map_output_sorangium/BiG-MAP.GCF_HGF.rev.1.bt2.tmp to /scratch3/dow17n/RNA_pilot/big-map/big-map_map_output_sorangium/BiG-MAP.GCF_HGF.rev.1.bt2
Renaming /scratch3/dow17n/RNA_pilot/big-map/big-map_map_output_sorangium/BiG-MAP.GCF_HGF.rev.2.bt2.tmp to /scratch3/dow17n/RNA_pilot/big-map/big-map_map_output_sorangium/BiG-MAP.GCF_HGF.rev.2.bt2
__________Fastq-files_________________________________
5_R1.fastq
6_R1.fastq
7_R1.fastq
8_R1.fastq
9_R1.fastq
______________________________________________________
5_R2.fastq
6_R2.fastq
7_R2.fastq
8_R2.fastq
9_R2.fastq
Mapping reads using bowtie
  Dealing with sample 5
Traceback (most recent call last):
  File "/apps/big-map/230322/bin/BiG-MAP.map.py", line 1129, in <module>
    main()
  File "/apps/big-map/230322/bin/BiG-MAP.map.py", line 1027, in main
    core_RPKM_avg = familycorrect(core_RPKM_avg, BGCF)
  File "/apps/big-map/230322/bin/BiG-MAP.map.py", line 731, in familycorrect
    for HGF_member in family[GC]:
TypeError: string indices must be integers

The bowtie2 log is as follows:
#5
71632055 reads; of these:
  71632055 (100.00%) were paired; of these:
    71602250 (99.96%) aligned concordantly 0 times
    29011 (0.04%) aligned concordantly exactly 1 time
    794 (0.00%) aligned concordantly >1 times
    ----
    71602250 pairs aligned concordantly 0 times; of these:
      173 (0.00%) aligned discordantly 1 time
    ----
    71602077 pairs aligned 0 times concordantly or discordantly; of these:
      143204154 mates make up the pairs; of these:
        143201511 (100.00%) aligned 0 times
        2565 (0.00%) aligned exactly 1 time
        78 (0.00%) aligned >1 times
0.04% overall alignment rate

Anyone got any bright ideas?
Lachlan

**Comment by nlouwen** [comment]
Thanks so much for opening an issue on this, it should be fixed in the new v1.1.0 release!
