### ISSUE TITLE
make_sketch() missing required arguments: 'kmer' and 'sketch'

### ISSUE THREAD

**Issue by snayfach** [medema-group/BiG-MAP#4]
Hello - I've just downloaded the tool and am getting started. Tried a test run but ran into the error below. Adding `-k 16 -s 5000` did not solve the issue:

` python BiG-MAP/src/BiG-MAP.family.py -p 8 -D bgcs -O test `

> ___________Extracting fasta files__________
> Traceback (most recent call last):
>   File "BiG-MAP/src/BiG-MAP.family.py", line 1219, in <module>
>     main()
>   File "BiG-MAP/src/BiG-MAP.family.py", line 1061, in main
>     make_sketch(args.outdir + os.sep)
> TypeError: make_sketch() missing 2 required positional arguments: 'kmer' and 'sketch'

**Comment by snayfach** [comment]
Running into several other issues now.  For example on ~ line 197:
`absolute_loc_start = record.annotations["structured_comment"]["antiSMASH-Data"]["Orig. start"]`

However, the "Orig. start" key is not in record.annotations["structured_comment"]["antiSMASH-Data"] for my genbank files. It might be helpful is there were a small test dataset that could be quickly run

**Comment by HAugustijn** [comment]
BiG-MAP.family takes output produced by antiSMASH/gutSMASH as input. Did you run one of these tools on your genbank files before using them as input for BiG-MAP?
