### ISSUE TITLE
SameFileError while running BiG-MAP.family.py 

### ISSUE THREAD

**Issue by razz1618** [medema-group/BiG-MAP#6]
HI,
Ran into the following error while running the latest commit:

home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py -p 30 -D 3.Function/antismash/ -b /home/mcs/soft/BiG-SCAPE/bigscape.py -pf /home/mcs/soft/BiG-SCAPE/ -O 3.Function/antismash/big_map_antismash -g True
Extracting fasta files
Preparing BiG-SCAPE input_
Traceback (most recent call last):
File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 1236, in 
main()
File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 1117, in main
movegbk(args.outdir, gbk_file, list_gbkfiles)
File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 828, in movegbk
shutil.copy(gbk_file, os.path.join(path, genome))
File "/home/mcs/miniconda3/envs/BiG-MAP_process/lib/python3.6/shutil.py", line 241, in copy
copyfile(src, dst, follow_symlinks=follow_symlinks)
File "/home/mcs/miniconda3/envs/BiG-MAP_process/lib/python3.6/shutil.py", line 104, in copyfile
raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '3.Function/antismash/big_map_antismash/gbk_files/c_000000000001.region001.gbk' and '3.Function/antismash/big_map_antismash/gbk_files/c_000000000001.region001.gbk' are the same file

Seems like problem with shutil copy function

**Comment by HAugustijn** [comment]
This problem was caused by the selected output directory and has now been solved in the latest commit. Thank you for notifying us!

**Comment by razz1618** [comment]
Thanks. will try today
