### ISSUE TITLE
Error in BiG-MAP.family.py with --metatranscriptomes option

### ISSUE THREAD

**Issue by sklucas** [medema-group/BiG-MAP#7]
Hello, I've come across an error when using the `--metatranscriptomes` option in BiG-MAP.family.py. 

Code run:
```
python3 ../software/BiG-MAP/src/BiG-MAP.family.py -D results/metagenomics/09_BGC/ANTISMASH/prodigal_bins \
-O results/metagenomics/09_BGC/ANTISMASH/big-map/results_family \
-b ../software/BiG-SCAPE \
-pf ../software/BiG-SCAPE \
-p 16 --metatranscriptomes
```
Where the input -D is the path to a collection of AntiSMASH output directories.

The error message is below:
> Running BiG-MAP.family.py
___________Extracting fasta files__________
_________Adding housekeeping genes_________
Traceback (most recent call last):
  File "../software/BiG-MAP/src/BiG-MAP.family.py", line 1237, in <module>
    main()
  File "../software/BiG-MAP/src/BiG-MAP.family.py", line 1178, in main
    organism_name = organism[organism.index(".") + 1:]
ValueError: substring not found

Could be similar to issue #5?

Thank you for your help!

**Comment by razz1618** [comment]
Hi, 

I too encountered  an error while reading gbk file using the **metatranscriptomes** option in BiG-MAP.family script:

**Code**
``
python3 /home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py -p 50 -D 0.3.functional_annotation/antismash -b /home/mcs/soft/BiG-SCAPE/bigscape.py -pf /home/mcs/soft/BiG-SCAPE/ --metatranscriptomes -O 0.3.functional_annotation/antismash/BiG-MAP/family
___________Extracting fasta files__________
_________Adding housekeeping genes_________
Traceback (most recent call last):
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 1237, in <module>
    main()
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 1162, in main
    seqdb = prepareseqdb(genomedict[orgID], args.outdir + os.sep)
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 682, in prepareseqdb
    for record in gbkcontents:
  File "/home/mcs/miniconda3/envs/BiG-MAP_process/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 636, in parse
    with as_handle(handle, mode) as fp:
  File "/home/mcs/miniconda3/envs/BiG-MAP_process/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/mcs/miniconda3/envs/BiG-MAP_process/lib/python3.6/site-packages/Bio/File.py", line 113, in as_handle
    with open(handleish, mode, **kwargs) as fp:
**FileNotFoundError: [Errno 2] No such file or directory: '0.3.functional_annotation/antismash/antismash.gbk'**
``
My antismash output folder has transcripts.gbk (resulted from the transcripts.fasta ) and not antismash.gbk.

Though the code works smoothly by skipping **metatranscriptomes** option.

**Comment by HAugustijn** [comment]
Sorry for the inconvenience! With the latest commit, this problem should be solved. Let me know if you are still experiencing problems running this module.

**Comment by razz1618** [comment]
@HAugustijn Unfortunately with the latest commit the problem did not resolve for me. 

**python3 /home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py** **-p** 50 **-D** 0.3.functional_annotation/antismash **-b** /home/mcs/soft/BiG-SCAPE/bigscape.py **-pf** /home/mcs/soft/BiG-SCAPE/ **--metatranscriptomes**  **-O** 0.3.functional_annotation/antismash/BiG-MAP/family**
___________Extracting fasta files__________
_________Adding housekeeping genes_________
Traceback (most recent call last):
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 1220, in <module>
    main()
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 1148, in main
    seqdb = prepareseqdb(genomedict[orgID], args.outdir + os.sep)
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 676, in prepareseqdb
    for record in gbkcontents:
  File "/home/mcs/miniconda3/envs/BiG-MAP_process/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 636, in parse
    with as_handle(handle, mode) as fp:
  File "/home/mcs/miniconda3/envs/BiG-MAP_process/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/mcs/miniconda3/envs/BiG-MAP_process/lib/python3.6/site-packages/Bio/File.py", line 113, in as_handle
    with open(handleish, mode, **kwargs) as fp:
**FileNotFoundError: [Errno 2] No such file or directory: '0.3.functional_annotation/antismash/antismash.gbk'**

**Comment by HAugustijn** [comment]
I made an adjustment to the file naming system in the latest commit. Is this solving the problem?

**Comment by sklucas** [comment]
Hi Hannah,
I am not sure if it is related to @razz1618  issues, but a new error message is below. I pulled the latest commit and ran the same BiG-MAP.family.py command as my initial post (works without the --metatranscriptomes). I am running BiG-MAP.family.py in preparation for mapping metatranscriptomes with BiG-MAP.map.py (I hope I am going about this correctly!). 

>___________Extracting fasta files__________
_________Adding housekeeping genes_________
Traceback (most recent call last):
  File "../software/BiG-MAP/src/BiG-MAP.family.py", line 1229, in <module>
    main()
  File "../software/BiG-MAP/src/BiG-MAP.family.py", line 1154, in main
    if not os.path.isfile(genomedict[orgID]):
KeyError: 'str_mock_000039.region001.region001'

Thanks for your help!

**Comment by razz1618** [comment]
@HAugustijn . i encountered the same error as posted by @sklucas  with the latest pull.

___________Extracting fasta files__________
_________Adding housekeeping genes_________
Traceback (most recent call last):
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 1229, in <module>
    main()
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 1154, in main
    if not os.path.isfile(genomedict[orgID]):
KeyError: 'c00108_NODE_10..region001'

**Comment by HAugustijn** [comment]
The latest update didn't take some of the alternative filenames in consideration. The latest commit should be able to handle these. @razz1618 @sklucas does this solve your problem?

**Comment by razz1618** [comment]
Hi,
Unfortunately, it did not fix the problem. 

______Extracting fasta files__________
_________Adding housekeeping genes_________
Traceback (most recent call last):
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 1233, in <module>
    main()
  File "/home/mcs/soft/BiG-MAP/src/BiG-MAP.family.py", line 1158, in main
    if not os.path.isfile(genomedict[orgID]):
KeyError: 'c00108_NODE_10..108_length_20657_cov_82'

**Comment by sklucas** [comment]
I was able to run BiG-MAP.family.py with the --metatranscriptomes option with no errors after pulling the latest commits. Thanks for all your troubleshooting on this @HAugustijn !

**Comment by HAugustijn** [comment]
@razz1618 I have made some adjustments to the family module that should solve your problem. Let me know if you still encounter problems.
